### ISSUE TITLE
Adding an `ISSUE_TEMPLATE.md`

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/codeheat.org#103]
#### After seeing the references, We should add up a `ISSUE_TEMPLATE.md` as added in other repositories.

**Are you interested in fixing this issue :** 
Yes! :+1: 

---
> **References** :- 
https://github.com/fossasia/codeheat.org/issues/98
https://github.com/fossasia/codeheat.org/pull/102

**Comment by abishekvashok** [comment]
@0x48piraj any updates?

**Comment by mariobehling** [comment]
I would like to close this issue, as it is a small priority and probably not even necessary in a simple web repo.

**Comment by 0x48piraj** [comment]
Sorry guys, I forgot.
Thanks for clearing though.
