### ISSUE TITLE
Modify the image for query-server project

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/codeheat.org#105]
**Current Behavior**
![query-one](https://user-images.githubusercontent.com/22936570/35437324-e4303f30-02b7-11e8-8e62-02db98879830.png)

**Expected Behavior**
![query-2](https://user-images.githubusercontent.com/22936570/35437330-e98102da-02b7-11e8-9aeb-60e3dcd66ac4.png)

**Comment by mariobehling** [comment]
I dont see what is the problem.

**Comment by bhaveshAn** [comment]
@mariobehling Earlier we had the image where the buttons were used in the UI for the respective search engine and now the `query-server` is having dropdown menu for the search engines and also the radio buttons for `General`, `Image` and `Video`.
Buttons changed to Dropdown.
**Before the change**: Buttons
**After the change**: Dropdown
You might realize when focusing only on the image.
Let me know can you figure out the issue now.

**Comment by bhaveshAn** [comment]
Sure :+1:
