### ISSUE TITLE
Add Grand Prize Winners and Finalist Winners

### ISSUE THREAD

**Issue by mariobehling** [fossasia/codeheat.org#107]
Please add two sections similar to https://2016.codeheat.org/#winners for Grand Prize Winners and Finalist Winners and include images and links.

**Comment by vaibhavsingh97** [comment]
Claiming 👍

**Comment by anshumanv** [comment]
@vaibhavsingh97 Awaiting to see the winners and finalists on the website. :smile:

**Comment by vaibhavsingh97** [comment]
@anshumanv Will send the PR latest today 👍

**Comment by mariobehling** [comment]
Please add additional details and find better pictures without other people in the background.

**Comment by mariobehling** [comment]
* Also please move the section to the top (header, info section, winners, supported by...)
* Rename "Winners" to Grand Prize Winners
* Rename Finalists to Finalist Winners

**Comment by sarnava1** [comment]
@mariobehling can I work on this?

**Comment by sarnava1** [comment]
@akshatnitd can I help with this?

**Comment by akshatnitd** [comment]
Yes, @sarnava1

**Comment by mariobehling** [comment]
This was about 2018.codeheat.org and can be closed here.
