### ISSUE TITLE
Add info section below header

### ISSUE THREAD

**Issue by mariobehling** [fossasia/codeheat.org#110]
Other program sites of FOSSASIA have an info section. Please add a similar section below the header with the following info:
* 650+ students
650 registered in the Codeheat contest 2017/18 and learnt how to participate in the developer community with FOSSASIA.

* 2000+ merged pull requests
More than 2000 pull requests were merged during the contest. Participants also submitted scrum reports, wrote blog posts and created entirely new projects in the FOSSASIA community.

* 37 mentors
Mentors are developers, engineers, university students, professors, and generally contributors who love to share and be a part of our open source community. They help creating better software for a better and just world.

![screenshot from 2018-02-09 12-34-41](https://user-images.githubusercontent.com/1583873/36026383-0a311486-0d97-11e8-84f6-8326c4a11a73.png)

**Comment by ankurg22** [comment]
Claiming.
