### ISSUE TITLE
Change year to 2019 in timeline

### ISSUE THREAD

**Issue by susg** [fossasia/codeheat.org#134]
In the timeline section, at two places the date is displayed with the year 2010. It should be changed to 2019. And also below it is written Feb 2018. I think that should also be 2019.

**Comment by susg** [comment]
hi, this mistake is seen in the table beside it as well.

**Comment by abishekvashok** [comment]
@susg can you solve that as well pls? I am reopening.

**Comment by susg** [comment]
sure.
