### ISSUE TITLE
Problem in Grid Layout at "MENTORS" Section

### ISSUE THREAD

**Issue by maheshjindal** [fossasia/codeheat.org#136]
There is unwanted space between last two rows in the "MENTORS" section.

<img width="1416" alt="layout_issue" src="https://user-images.githubusercontent.com/30390269/45594098-76029c80-b9b2-11e8-8771-77ab44f910ab.png">
<img width="1390" alt="layout_issue2" src="https://user-images.githubusercontent.com/30390269/45594099-769b3300-b9b2-11e8-9574-6812a1c980cd.png">

**Comment by anshulahuja98** [comment]
can someone assign this issue to me?

**Comment by maheshjindal** [comment]
Sir, I am already working on the same issue.

**Comment by leoking-crey** [comment]
if this issue is still open,I am assigning it to myself

**Comment by mariobehling** [comment]
Seems to be fine currently.
