### ISSUE TITLE
Social link list is not in centre

### ISSUE THREAD

**Issue by subhahu123** [fossasia/codeheat.org#159]
social overlay link list which appears on hovering on image is not in centre 

![peek 2018-11-19 03-41](https://user-images.githubusercontent.com/34541684/48678726-1b054580-ebad-11e8-84b2-5b0f8d001f8e.gif)

**Comment by Sangatdas** [comment]
Can i be assigned this issue?

**Comment by mahamoutdogoy** [comment]
Is this issue still open? can I contribute?

**Comment by 15999shivam** [comment]
can i be assigned this issue?

**Comment by subhahu123** [comment]
> can i be assigned this issue?

yes , go ahead

**Comment by mariobehling** [comment]
Dont think this is an issue. It works.
