### ISSUE TITLE
Sign up button with red font instead of white

### ISSUE THREAD

**Issue by mariobehling** [fossasia/codeheat.org#17]
The sign up button in the timeline section has red front. It should be white. The button has the same class as the button on the header, but is still different.

Expected look:
![screenshot from 2016-09-24 09 59 34](https://cloud.githubusercontent.com/assets/1583873/18807052/e436d616-823d-11e6-83cf-d9ddf1c9a80d.png) 
http://codeheat.org/untitled.html#timeline

**Comment by SaptakS** [comment]
@mariobehling working on it..

**Comment by SaptakS** [comment]
@mariobehling fixed.
