### ISSUE TITLE
Add website, github, twitter, linkedin to all

### ISSUE THREAD

**Issue by mariobehling** [fossasia/codeheat.org#2]
Please add 
- [ ] website
- [ ] github
- [ ] twitter
- [ ] linkedin 
  to jury, mentors, organizers.

**Comment by SaptakS** [comment]
added my personal details [here](https://github.com/fossasia/codeheat.org/commit/ada0876bb494bb77b2c9219bdaa5b2fe699abefd)

**Comment by mariobehling** [comment]
@SaptakS Please add Github and would be great if you also help to add details of others.

**Comment by SaptakS** [comment]
@mariobehling will get it done.

**Comment by jig08** [comment]
@mariobehling Sure.
