### ISSUE TITLE
Add website generator to projects

### ISSUE THREAD

**Issue by mariobehling** [fossasia/codeheat.org#207]
Website generator is not listed yet.

**Comment by Dharmesh-Poddar** [comment]
@mariobehling can I work on it..

**Comment by liveHarshit** [comment]
> @mariobehling can I work on it..

Please go ahead.

**Comment by vinaysomawat** [comment]
@liveHarshit could you explain this issue? what is the meaning of "Website generator is not listed yet."?

**Comment by liveHarshit** [comment]
> @liveHarshit could you explain this issue? what is the meaning of "Website generator is not listed yet."?

Sorry, I'm not familiar with web D. @uds5501 @shreyanshdwivedi Can you please explain?

**Comment by uds5501** [comment]
@liveHarshit @vinaysomawat 
You have to make a project card for Open Event Website Generator Project : https://github.com/fossasia/open-event-wsgen

The project card inspirations can be taken from here
![image](https://user-images.githubusercontent.com/21087061/64485994-092c8600-d245-11e9-8ee7-d1974b33dc68.png)

**Comment by srishtiBajpai** [comment]
Is this issue still open?

**Comment by Dhruvibansal** [comment]
I want to fix this issue, is it still open ?

**Comment by HeroicHitesh** [comment]
@mariobehling @liveHarshit I see this issue is not fixed yet, also #208 is closed due to inactivity. If this issue is up-for-grab, I will like to work on it.

**Comment by naman360** [comment]
Can I work on this issue?
