### ISSUE TITLE
Remove Codeheat 2019 from about section

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/codeheat.org#210]
URL is not opening from about section: https://2019.codeheat.org/

**Comment by liveHarshit** [comment]
@mariobehling Where is the repo gone: https://github.com/fossasia/2019.codeheat.org

**Comment by abishekvashok** [comment]
It's codeheat.org

**Comment by liveHarshit** [comment]
> It's https://codeheat.org

What? Please go to about section. Where is the repo for codeheat 2018/19 context??

**Comment by liveHarshit** [comment]
> It's https://codeheat.org

Oh, It's changed to Codeheat 2018. Earlier it was 2019.codeheat.org. Cheak in about section on 2019.codeheat.org.

**Comment by asha15** [comment]
@liveHarshit Shall i work on this?

**Comment by liveHarshit** [comment]
> @liveHarshit Shall i work on this issue?

Go ahead.

**Comment by asha15** [comment]
@liveHarshit Can i know how to resolve this error? 

![Screenshot (287)](https://user-images.githubusercontent.com/28682701/64923916-68b60300-d7fc-11e9-9e8a-ddb4693261d2.png)

**Comment by liveHarshit** [comment]
> @liveHarshit Can i know how to resolve this error?
> 
> ![Screenshot (287)](https://user-images.githubusercontent.com/28682701/64923916-68b60300-d7fc-11e9-9e8a-ddb4693261d2.png)

What?
Please go through https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by abishekvashok** [comment]
@asha15 make a pull request instead of trying to directly push to the upstream repo. I see that you haven't forked the repo either, so pls refer to the guide mentioned above.

**Comment by asha15** [comment]
@abishekvashok @liveHarshit Thank you for the explanation.
I have send a pull request.Kindly request you to review it
