### ISSUE TITLE
Page Responsiveness Issue

### ISSUE THREAD

**Issue by Dishebh** [fossasia/codeheat.org#217]
### Description:
There are some bugs in the participating projects section of the web page, like the projects cards do not align in a proper way as should be done by bootstrap grid system (at 1180 x 1329 resolution).

### Steps to reproduce: 
1. Go to the (webpage)[https://codeheat.org]
2. Head to the Participating Projects section.
3. Change the resolution to 1180 x 1329 px.

### Screenshot of the issue:
![Screenshot from 2019-12-23 01-35-51](https://user-images.githubusercontent.com/43489708/71326837-61527400-2526-11ea-9342-013750da2314.png)

**Comment by rajamanojkumar** [comment]
can i work on this issue

**Comment by Dishebh** [comment]
> can i work on this issue

There's already a PR open for it. Pls find some other issue until the PR is resolved.

**Comment by HeroicHitesh** [comment]
@Dishebh I guess you can close this issue now as your PR is merged, which I believe resolves this issue.
