### ISSUE TITLE
Many of the yellow links are overlapping with the text and need to be fixed.

### ISSUE THREAD

**Issue by Chaitanyassr** [fossasia/codeheat.org#219]
![Screenshot (136)](https://user-images.githubusercontent.com/30374226/72013448-dee6e580-3283-11ea-9780-e9a7ca50a540.png)

**Comment by abishekvashok** [comment]
Go on and fix em

**Comment by Chaitanyassr** [comment]
oh! a pr is already there.

**Comment by vibhuti019** [comment]
Is the  issue fixed

**Comment by Deeksha2501** [comment]
I would like to fix the issue

**Comment by Chaitanyassr** [comment]
Hi @Deeksha2501 , A PR is already there for this issue also and it is approved by 2 members. it would be suggested to hold of for this issue.

**Comment by prajaktatamte** [comment]
I would like to fix the issue.

**Comment by The-Keshav-Agarwal** [comment]
is this issue is still open? I would like to work on this issue.

**Comment by Deeksha2501** [comment]
ok :)

**Comment by akhil27styles** [comment]
give me a chance I will try to fix this issue

**Comment by Anamika810** [comment]
I will be obliged if I'll be given a chance to fix this issue.

**Comment by Dhruvibansal** [comment]
I would like to fix this issue .Is it still open ?

**Comment by rcoder23** [comment]
i can fix this issue

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by mayank0811** [comment]
i want to work on this issue.

**Comment by Raunaksingh100** [comment]
@mariobehling and @Chaitanyassr 
![Uploading 2.PNG…]()
 this bug is already fixed you can close this issue

**Comment by anjali1102** [comment]
I want to contribute to codeheat. But there are almost no issues overhere...sad😔

**Comment by sayak2k1maruti** [comment]
Please give me a chance to fix this issue

**Comment by Raunaksingh100** [comment]
### this is issue already fixed see in the official website aur see in the screenshot below-
![1](https://user-images.githubusercontent.com/65535360/98459676-0750b080-21c3-11eb-8d96-078aa87496bb.PNG)

**Comment by Afzal-Ind** [comment]
@mariobehling Hi, You can close this issue since it seems this issue fixed. Thanks. [Click here](https://codeheat.org/)

**Comment by Kerveyfelix** [comment]
Can I fix this issue?

**Comment by SaranshMaheshwari** [comment]
Can I work on this issue ?

**Comment by Sloth-Panda** [comment]
Can I work on this?

**Comment by Raunaksingh100** [comment]
> ### this is issue already fixed see in the official website aur see in the screenshot below-
> so no need to work on this issue
> ![1](https://user-images.githubusercontent.com/65535360/98459676-0750b080-21c3-11eb-8d96-078aa87496bb.PNG)
> 

See this

**Comment by Cipher-08** [comment]
Is it still a issue??

**Comment by ayushporwal1234** [comment]
i can solve this !! CAN  YOU GIVE ME A CHANCE ?
