### ISSUE TITLE
Fix CSS in Finalist Winners section

### ISSUE THREAD

**Issue by janethavi** [fossasia/codeheat.org#226]
It would be much nice if we can add the CSS settings of the Jury section to the Finalist Winners section.

Something like this.
![Screenshot from 2020-03-24 19-16-13](https://user-images.githubusercontent.com/35697678/77432408-07eb3100-6e04-11ea-8673-9df6c5cba0f2.png)

**Comment by Deeksha2501** [comment]
I would like to work on this issue

**Comment by prajaktatamte** [comment]
@janethavi I would like to work on this issue.

**Comment by prathmeshkhandelwal1** [comment]
i want to fix this issue

**Comment by MDivakarPal** [comment]
@janethavi  Can i Work on this issue
