### ISSUE TITLE
Grand Prize winners not properly alligned

### ISSUE THREAD

**Issue by Siddharth1698** [fossasia/codeheat.org#235]
![Screenshot from 2020-06-04 23-17-06](https://user-images.githubusercontent.com/31384057/83793016-8a705680-a6b9-11ea-80a2-4f0ef98c23c7.png)
Here the two images seems to be together while first image bit far. It doesn't look good.

**Comment by Siddharth1698** [comment]
I will fix it like other images are alligned

**Comment by viplav153** [comment]
hey i want to fix this issue please  assign me for this

**Comment by Siddharth1698** [comment]
@viplav153  i already fixed it and send a PR

**Comment by UniqueWebpageDesign** [comment]
working on it

**Comment by neeraj-2** [comment]
#249 (comment).
I updated index.html file and now it looks like as shown:
![allignment_after_change2](https://user-images.githubusercontent.com/56186425/91454170-45b22100-e89e-11ea-86a2-97db0f9ecc1e.PNG)

I have attached a PR here .Please review it
