### ISSUE TITLE
Image responsiveness issue in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/codeheat.org#238]
Image responsiveness issue in mobile view 
![issue](https://user-images.githubusercontent.com/65535360/86391693-d4982800-bcb7-11ea-9d9e-19ee021498be.jpg)

**Comment by ajaxpraps** [comment]
hey ,can i work on this issue.

**Comment by Raunaksingh100** [comment]
go ahead

**Comment by anilmaurya61** [comment]
i wanna work on this issue.

**Comment by Raunaksingh100** [comment]
@anilmaurya61 no need of assigning just fixed the issue and generate the pr .........

**Comment by fluorspar20** [comment]
Is this issue still open? I would like to work on it.

**Comment by Raunaksingh100** [comment]
@fluorspar20  go ahead

**Comment by shivalikadevi** [comment]
I want to work on this issue.

**Comment by anilmaurya61** [comment]
![codeheat](https://user-images.githubusercontent.com/56387037/94467525-b8395800-01e0-11eb-8171-a93c5accd6a4.jpg)

https://github.com/fossasia/codeheat.org/pull/270

**Comment by mariobehling** [comment]
This is working as expected. No changes are needed.
