### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sapna2001** [fossasia/codeheat.org#239]
Grammatical errors like,
1." friends and partners." instead of " friends, and partners."
2." necessitate a closure " instead of "necessitate the closure"

**Comment by Sapna2001** [comment]
can I work on this?

**Comment by khushboojoshi3** [comment]
**Initially, it was-**
If you don't know what does squashing of commits is read from here.
**After Changes-**
If you don't know what does squashing of commits means, then read it from [here](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec).

_**Can I work on this issue?**_

**Comment by mariobehling** [comment]
Focus is the website itself. Readme is secondary and out of scope.
