### ISSUE TITLE
mentors and jury members images are not aligning in the center in some smaller screen sizes

### ISSUE THREAD

**Issue by anu-007** [fossasia/codeheat.org#24]
all the images of mentors and jury members are not aligning in center for screen size below 765*876.
![screenshot from 2016-09-28 00-24-26](https://cloud.githubusercontent.com/assets/20153241/18887557/2c306ec4-8512-11e6-9c6e-8dfbd63223a2.png)
![screenshot from 2016-09-28 00-25-00](https://cloud.githubusercontent.com/assets/20153241/18887555/2bdce196-8512-11e6-9d7c-4ee7346646c6.png)

**Comment by jig08** [comment]
@anu-007 Would you like to resolve this ?

**Comment by jig08** [comment]
@anu-007 Sorry, it seems to work fine now. Closing this issue.
