### ISSUE TITLE
Navbar overlaps content at desktop site in mobile view

### ISSUE THREAD

**Issue by anilmaurya61** [fossasia/codeheat.org#244]
Screenshot for better understanding.

![WhatsApp Image 2020-07-10 at 3 45 33 AM](https://user-images.githubusercontent.com/56387037/87174102-aa1f0f80-c261-11ea-9b6e-df29200e356b.jpeg)

**Comment by Samiksha99** [comment]
i think it is already resolved

**Comment by anilmaurya61** [comment]
> i think it is already resolved

No,not yet.

**Comment by Samiksha99** [comment]
![Screenshot from 2020-07-12 20-02-23](https://user-images.githubusercontent.com/55537242/87249246-9222d800-c47b-11ea-8397-3f8d1bca9d94.png)
see in mobile view its fine

**Comment by Samiksha99** [comment]
![WhatsApp Image 2020-07-12 at 8 13 15 PM](https://user-images.githubusercontent.com/55537242/87249339-2ee57580-c47c-11ea-9365-a1f44b37b9f4.jpeg)
i saw this in mobile view its fine

**Comment by Manish-Kumarr** [comment]
@Samiksha99 It is overlapping b/w screen size 970px - 991px

**Comment by Samiksha99** [comment]
okay yes

**Comment by Manish-Kumarr** [comment]
Can i work on this issue ?

**Comment by anilmaurya61** [comment]
> Can i work on this issue ?

Go ahead !!

**Comment by shivalikadevi** [comment]
Can i work on this  issue?

**Comment by 26Vinayak** [comment]
I would like to work on this issue

**Comment by Raunaksingh100** [comment]
now i saying thrice as eariler i already fixed this bug plz find some others issue
