### ISSUE TITLE
Icons are not align in center while hovering

### ISSUE THREAD

**Issue by Manish-Kumarr** [fossasia/codeheat.org#245]
Icons are not aligned center while hovering on the image
Screen size between 992px to 1200px

![Annotation 2020-07-13 114824](https://user-images.githubusercontent.com/53834930/87277035-1ec2aa00-c4ff-11ea-9f21-df667f48bcf2.png)

@mariobehling I would like to work on this issue

**Comment by prodiptahalder** [comment]
Is anyone working on this issue! I would like to work on this.

**Comment by Manish-Kumarr** [comment]
yes, I am

**Comment by saideepesh000** [comment]
@Manish-Kumarr, are you still working on it?

**Comment by Manish-Kumarr** [comment]
yes, I am but till now no one's assigning me that's why i am waiting for PR.

**Comment by shivalikadevi** [comment]
Hey is this issue still open .I want to work on this issue.

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by Devansh3712** [comment]
@mariobehling may i work on this issue?

**Comment by 26Vinayak** [comment]
i would like to work on this issue.
any assign me?

**Comment by Raunaksingh100** [comment]
i already fixed this issue now plz find some other issues thanks

**Comment by mariobehling** [comment]
This section does not exist in current page. The website seems good enough to achieve its goal. There does not seem to be major issues. At FOSSASIA we try to have working websites, but our main energy we try to put into projects. Thanks.
