### ISSUE TITLE
A Simple Grammatical Error in Readme file.

### ISSUE THREAD

**Issue by neeraj-2** [fossasia/codeheat.org#248]
**Initial Readme File with error  as shown :**
![Readme](https://user-images.githubusercontent.com/56186425/90961823-2e9fb780-e4c9-11ea-9401-3ed879100673.png)
I just found some grammatical mistakes while reading Readme file .I have attached the screenshot where i got those errors.

**Comment by mariobehling** [comment]
Focus is the website itself. Readme is secondary and out of scope.
