### ISSUE TITLE
project dropdown menu does not collapse after clicking project again in navbar

### ISSUE THREAD

**Issue by anu-007** [fossasia/codeheat.org#25]
in navbar the dropdown menu corresponding to projects does not collapse automatically after removing mouse from it or by clicking projects again.
![screenshot from 2016-09-28 00-37-06](https://cloud.githubusercontent.com/assets/20153241/18887937/f69c4650-8513-11e6-83cd-f24df2f60ccb.png)
![screenshot from 2016-09-28 00-38-15](https://cloud.githubusercontent.com/assets/20153241/18887939/f794587c-8513-11e6-90da-5f12c9c93c30.png)

**Comment by sandmanx** [comment]
It is working fine. I couldn't find any problem.

**Comment by jig08** [comment]
Works fine for me too. 
Closing this issue.

**Comment by anu-007** [comment]
have you checked it for smaller screen size like 485*879

**Comment by jig08** [comment]
@anu-007 Just checked, seems fine there as well.
