### ISSUE TITLE
Collapse property of menu bar

### ISSUE THREAD

**Issue by neeraj-2** [fossasia/codeheat.org#250]
Actual Behaviour:

In Mobile view,menu does not collapse by itself.

Expected Behaviour:

After  choosing some option,menu should be collapsed by itself.

Would you like to work on the issue?
Open for all!

![menu](https://user-images.githubusercontent.com/56186425/91535917-873fdc00-e931-11ea-8122-8a6c18366480.PNG)

**Comment by saideepesh000** [comment]
@neeraj-2, can I work on this issue

**Comment by neeraj-2** [comment]
Nice Work @saideepesh000

**Comment by saideepesh000** [comment]
> 
> 
> Nice Work @saideepesh000

@neeraj-2, thanks
