### ISSUE TITLE
Add dark Theme

### ISSUE THREAD

**Issue by sagar-barapatre** [fossasia/codeheat.org#252]
Save our eyes. And batteries. Do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by k-guy-dev** [comment]
@sagar-barapatre hey! I would like to take this one. I've attached a screenshot of my take on this issue.
![Screenshot_2020-09-15 Code Heat Coding Contest of FOSSASIA](https://user-images.githubusercontent.com/56889834/93235564-5f5ad000-f79b-11ea-9abf-8cb9955c228b.jpg)

**Comment by sagar-barapatre** [comment]
Great buddy ! Go ahead and make a PR
