### ISSUE TITLE
Back to top button need alignment

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/codeheat.org#253]
### Description-
the "Back-to-top" button need to be right not to be center see in the screenshot given below for the better understanding..

### screenshot-
![now](https://user-images.githubusercontent.com/65535360/92367840-93d3e980-f114-11ea-8b98-b1d4405cceeb.PNG)

**Comment by ooyeraju** [comment]
can I take this ?

**Comment by Raunaksingh100** [comment]
@ooyeraju  go ahead!!

**Comment by Srijan205** [comment]
Can i take this??

**Comment by Raunaksingh100** [comment]
> Can i take this??

Go ahead

**Comment by ooyeraju** [comment]
I'm working on this 😅.

Thanks and Regards
Rajnish Kumar
Second Year Undergraduate Student
Department of Humanities and Social Sciences
Indian Institute of Technology, Kharagpur
West Bengal, India

**Comment by ooyeraju** [comment]
Can you please give me 2 days. If not you someone else can go for it.

Thanks and Regards

Rajnish Kumar
Second Year Undergraduate Student
Department of Humanities and Social Sciences
Indian Institute of Technology, Kharagpur
West Bengal, India

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by yash0501** [comment]
Can I work on this issue?

**Comment by khushishikhu** [comment]
may i work on this issue

**Comment by Raunaksingh100** [comment]
> may i work on this issue

No ,There is already pr for this

**Comment by mayank0811** [comment]
can i work on this issue?
