### ISSUE TITLE
Grand prize winners not properly aligned.

### ISSUE THREAD

**Issue by deepti23-web** [fossasia/codeheat.org#257]
Grand prize winners not properly aligned in desktop view.
![Capture](https://user-images.githubusercontent.com/64003317/93258512-0a7b8180-f7bc-11ea-9bd7-5dc44cf693f5.PNG)

**Comment by BhuwanChandra** [comment]
@deepti23-web are you working on this issue? I would like to work on this issue.

**Comment by deepti23-web** [comment]
No. Go ahead @BhuwanChandra .

**Comment by shivalikadevi** [comment]
I will like to work on this issue.
