### ISSUE TITLE
Mentors Section of the page layout is not properly displaying

### ISSUE THREAD

**Issue by max-keviv** [fossasia/codeheat.org#261]
Reduce the screen size to see the effect

NOW:
![Screenshot (51)](https://user-images.githubusercontent.com/59287619/93705571-16f53680-fb3c-11ea-8366-3756b7d00785.png)
unexpected blank between cards
EXPECTED:
![Screenshot (53)](https://user-images.githubusercontent.com/59287619/93705573-1bb9ea80-fb3c-11ea-8f1b-2880f3d13428.png)

actual behaviour

**Comment by daretobedifferent18** [comment]
I would like to work on this issue.

**Comment by max-keviv** [comment]
Go on

**Comment by daretobedifferent18** [comment]
I have fixed it PR #266 . Please have a review and if it is ok merge it.
