### ISSUE TITLE
text is not aligned vertically in tablet view

### ISSUE THREAD

**Issue by chait04** [fossasia/codeheat.org#269]
![Screenshot (13)_LI](https://user-images.githubusercontent.com/59140343/94328955-8784d300-ffd4-11ea-93b8-38df55672e1b.jpg)

**Comment by chait04** [comment]
I would to work on this issue

**Comment by shivalikadevi** [comment]
I will like to work on this issue .As I am new to this repo please guide me

**Comment by shashwattpandeyy** [comment]
I would like to work on this issue..

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by yash0501** [comment]
I would like to work on this issue.

**Comment by chait04** [comment]
> I will like to work on this issue .As I am new to this repo please guide me

Go ahead

**Comment by 26Vinayak** [comment]
may i work on this issue?

**Comment by swapnil-code** [comment]
i will work on this issue

**Comment by Roshanpaswan** [comment]
I will work on this issue this is my first attempt

**Comment by Arnab9674** [comment]
i want to work on it

**Comment by Himanshunitrr** [comment]
I will to work on this issue. What is the path where you captured this screenschot sir?

**Comment by chait04** [comment]
issue solved
