### ISSUE TITLE
links are open in the same page

### ISSUE THREAD

**Issue by himanshujaidka** [fossasia/codeheat.org#271]
all links are open in the same page, pls assign this to me

**Comment by mrunalvilas** [comment]
I will be obliged if I'll be given a chance to fix this issue.

**Comment by Raunaksingh100** [comment]
> all links are open in the same page, pls assign this to me

@himanshujaidka can you make the proper issue with description so, that  the user and the mentors can understand ...

**Comment by himanshujaidka** [comment]
it is clear to all the mentors or maybe to contributors, I think because they are familiar with it

**Comment by Raunaksingh100** [comment]
> it is clear to all the mentors or maybe to contributors, I think because they are familiar with it 

But new contributers are not familiar with this

**Comment by naman360** [comment]
Can I work on it?

**Comment by himanshujaidka** [comment]
please mentors have a look in it

**Comment by mariobehling** [comment]
This is as it should be.
