### ISSUE TITLE
Spelling mistake in PSLab Android tile in "Participating Projects" section

### ISSUE THREAD

**Issue by MananKGarg** [fossasia/codeheat.org#273]
The paragraph under the PSLab Android title ends with, "......... Pocket Science Lab we can do lots of experiments and even control robots with up to four servors." 

The last word should be "servos". (servos used in robots)

![WhatsApp Image 2020-09-30 at 11 21 19](https://user-images.githubusercontent.com/62146744/94648026-4dd30580-030f-11eb-8e59-33ea4d983f00.jpeg)

**Comment by MananKGarg** [comment]
Please assign this issue to me. I have already figured out the fix.

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by vj-codes** [comment]
I would like to work on this
