### ISSUE TITLE
No proper alignment in participating project.

### ISSUE THREAD

**Issue by adnanraghib1308** [fossasia/codeheat.org#293]
![Screenshot 2020-12-10 at 11 58 12 PM](https://user-images.githubusercontent.com/56679676/101814452-32bd1700-3b44-11eb-9333-fa5db70509f1.jpg)

**Comment by adnanraghib1308** [comment]
I am working on this issue

**Comment by Raunaksingh100** [comment]
> I am working on this issue
> 

Plz work on projects of FOSSAISA not on the simple website

We don't focus on this simple website thanks.

**Comment by MohitPatni0731** [comment]
Can I work on this issue.
