### ISSUE TITLE
Add space between Finalist winner

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/codeheat.org#303]
### description-
Add space between in Finalist winner see in the screenshot for the better understanding

### screenshot
![12](https://user-images.githubusercontent.com/65535360/102350274-ab9bf300-3fca-11eb-9e82-a38eaa5660a2.PNG)

**Comment by MohitPatni0731** [comment]
Can I work on this issue.

**Comment by Raunaksingh100** [comment]
> Can I work on this issue.

Yes go ahead and plz only margin of 10 px in my photo thanks

**Comment by saumyasrivastava08** [comment]
can i work on this?

**Comment by Raunaksingh100** [comment]
> can i work on this?
> 

No it lead to duplicate work

**Comment by Raunaksingh100** [comment]
@saumyasrivastava08   no need assign fixed this bug and create PR for this

**Comment by MohitPatni0731** [comment]
I am already working on it

**Comment by Raunaksingh100** [comment]
@MohitPatni0731 plz create pr for this anyone can fixed the bug and create pr for thid

**Comment by MohitPatni0731** [comment]
Sure will do that

**Comment by cggvuhh** [comment]
@MohitPatni0731 how much time you take to fixed this simple issue??????

or I will fixed this issue

**Comment by saumyasrivastava08** [comment]
@Raunaksingh100  can i work on any other issue

**Comment by Raunaksingh100** [comment]
> @Raunaksingh100  can i work on any other issue
> 

No there is already pr for it .
