### ISSUE TITLE
No-Space-between-Mentor-Images

### ISSUE THREAD

**Issue by Naman-1234** [fossasia/codeheat.org#309]
![Screenshot (714)_LI](https://user-images.githubusercontent.com/63748249/102911263-cd511a80-44a1-11eb-805e-a811a709fc36.jpg)

As you can see in the photo, there is no gap between Mentor Images,  They appears to be overlapping, A little margin between them will make them look nice.

Can i work on this issue

**Comment by Samridhi-98** [comment]
I would like to work on this issue please assign me.

**Comment by Raunaksingh100** [comment]
@Naman-1234 this is not an issue this is designed 
You can closed this issued

**Comment by Naman-1234** [comment]
Ok @Raunaksingh100
