### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by satcasm** [fossasia/codeheat.org#316]
It seems like there should be a link present at "here" and also a "fullstop(.)" at the end of the paragraph.

Relevant Screenshot:
![image](https://user-images.githubusercontent.com/56315878/106354822-6897a400-631a-11eb-8481-33a0d88ffae7.png)

**Comment by shrutikolk** [comment]
Can I fix this issue?

**Comment by OnkarNora** [comment]
It looks like [this](https://gist.github.com/patik/b8a9dc5cd356f9f6f980) link should be added.
