### ISSUE TITLE
Open-Event Web project's image needs to be changed on the webpage

### ISSUE THREAD

**Issue by afzal442** [fossasia/codeheat.org#334]
The existing image of the Open-eventyay project under the participating project is outdated. Plz, change that.

Plz look at image for a better understanding
![s1](https://user-images.githubusercontent.com/11625672/111894215-ed579200-8a2e-11eb-860f-1d3f49c3c506.JPG)

Find the required image on the eventyay.com webpage itself and replace the existing one with that image.

**Comment by adilshehzad786** [comment]
Please Assign me the following Issue. 
I am working on this Issue. 
Should I capture an updated Image from here: https://eventyay.com/

**Comment by afzal442** [comment]
Thanks @adilshehzad786. `Should I capture an updated Image from here: https://eventyay.com/` Yep, u can. U don't need to be assigned. U can make a PR for this. Let me know if u need any help.

**Comment by adilshehzad786** [comment]
I Updated the Image to the latest one 
Preview is available here: https://github.com/fossasia/codeheat.org/pull/337

**Comment by afzal442** [comment]
Closed for #337
