### ISSUE TITLE
Grammatical Mistake in Readme.md file!!!

### ISSUE THREAD

**Issue by khanjasir90** [fossasia/codeheat.org#340]
![Capture23](https://user-images.githubusercontent.com/53305380/122808129-10be0180-d2ea-11eb-9f6b-9508d2a15df2.JPG)

It should actually be "Heat of Code is a Coding Contest run by FOSSASIA, friends and partners."
OR
It should actually be "Codeheat is a Coding Contest run by FOSSASIA, friends and partners."

**Comment by khanjasir90** [comment]
@mariobehling @abishekvashok  can i work on this?

**Comment by Raunaksingh100** [comment]
@khanjasir90 this is not a bug.
