### ISSUE TITLE
Fix the alignment of text-links in the projects section

### ISSUE THREAD

**Issue by RavicharanN** [fossasia/codeheat.org#38]
A few text-links in the info box are aligned to the right unlike the others.
**Screenshot:**
![screen shot 2017-09-06 at 5 00 50 pm](https://user-images.githubusercontent.com/22046387/30110253-1390612a-9327-11e7-93f2-d18236761726.png)

**Comment by niccokunzmann** [comment]
Yes, sure! Your PR is welcome to improve the site for all other people.

**Comment by RavicharanN** [comment]
Since the issue is fixed, I'm closing it now.
