### ISSUE TITLE
Alignment of `Codeheat` in the front page 

### ISSUE THREAD

**Issue by mish24** [fossasia/codeheat.org#41]
![screenshot from 2017-09-06 16-10-18](https://user-images.githubusercontent.com/24610197/30122458-083df200-931e-11e7-86d8-20a454eaf489.png)

`Codeheat` isn't aligned properly with the other links in the header.

**Comment by niccokunzmann** [comment]
Would you like to fix that? You can mention this issue with #41 in the pull-request.

**Comment by mish24** [comment]
@niccokunzmann Yes! I will work on this!

**Comment by niccokunzmann** [comment]
Fixed in #45 by @mish24.
