### ISSUE TITLE
Add more information about working on improving the pages in the Readme

### ISSUE THREAD

**Issue by mish24** [fossasia/codeheat.org#42]
In my opinion we can add more information about branches and other contributing guidelines in the `README.md` file. Shall I go ahead?

**Comment by niccokunzmann** [comment]
Sure, please create a pull-request. If you mention this issue as "fix #42" in the commit comment, merging it will automaticaly close this issue.

**Comment by vaibhavsingh97** [comment]
@niccokunzmann Since, She is not active so i am claiming this issue 😄

**Comment by mariobehling** [comment]
The goal of this repo is not really to solve lots of issues. We rather need help in the software applications at FOSSASIA. We have an article at https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ Therefore closing it.

**Comment by vaibhavsingh97** [comment]
@mariobehling I just cleaning the issues so that's why asked to claimed 👍
