### ISSUE TITLE
Wrong Github link on Codeheat Registration page

### ISSUE THREAD

**Issue by Man-Jain** [fossasia/codeheat.org#43]
The Github link of the fossasia is wrong on the Codeheat registration Google form. 
https://docs.google.com/forms/d/e/1FAIpQLSfhIZHnDIFwHZjRHrp1LmzcBE5eaAtudCFgQKEoFwxb229Ulw/viewform

![fossasia_github_err](https://user-images.githubusercontent.com/12700384/30124014-8f1dfc38-9351-11e7-808b-3a731aefeef2.jpg)

**Comment by niccokunzmann** [comment]
Very observant. But I do not know who generated the form. What do you think? Does clicking the link direct to the correct page?

**Comment by niccokunzmann** [comment]
@Man-Jain Maybe this can be reported like this: https://groups.google.com/forum/#!topic/fossasia/tqLIph58icM

**Comment by mish24** [comment]
@niccokunzmann This has already been reported on the slack channel as well. I remember they said they'll fix it soon :)

**Comment by Man-Jain** [comment]
Thanks @niccokunzmann for the suggestion. I will follow it in the future.

**Comment by niccokunzmann** [comment]
I will close the issue since this is not the place for it. Thanks @Man-Jain for reporting it!
