### ISSUE TITLE
The nav-bar contents overlap with the "Codeheat" for particular screen-dimensions 

### ISSUE THREAD

**Issue by RavicharanN** [fossasia/codeheat.org#44]
The contents of the nav-bar overlap with the "Codeheat" for a set of resolutions.

Screenshot : 

![screen shot 2017-09-07 at 1 03 03 am](https://user-images.githubusercontent.com/22046387/30131007-ca243fec-9368-11e7-8303-377dc7ef0e32.png)

**Comment by niccokunzmann** [comment]
Thanks for reporting. Would you like to work on this or give others the chance?

**Comment by RavicharanN** [comment]
@niccokunzmann I'll work on it if it's okay.

**Comment by niccokunzmann** [comment]
Sure.

**Comment by niccokunzmann** [comment]
closed by #46.
