### ISSUE TITLE
Link errors on google docs form

### ISSUE THREAD

**Issue by pierreneter** [fossasia/codeheat.org#50]
Hi there,
This is `github.com`, not `github.org`.

At your form: https://docs.google.com/forms/d/e/1FAIpQLSfhIZHnDIFwHZjRHrp1LmzcBE5eaAtudCFgQKEoFwxb229Ulw/viewform

![form](https://user-images.githubusercontent.com/12815768/30246133-6d2b3132-961b-11e7-97fb-6b8f058d6cc7.PNG)

**Comment by isuruAb** [comment]
@mariobehling please check this issue

**Comment by troublemagnet** [comment]
I'd like to work on this.

**Comment by mariobehling** [comment]
Corrected. Thanks.
