### ISSUE TITLE
arrange images of mentor section correctly

### ISSUE THREAD

**Issue by isuruAb** [fossasia/codeheat.org#67]
arrange images of mentor section correctly.

<img width="1220" alt="screen shot 2017-09-16 at 4 24 26 pm" src="https://user-images.githubusercontent.com/7692626/30511661-a9cacd16-9afb-11e7-9915-a86f8c1c29d4.png">

**Comment by Vishesh-Gupta** [comment]
I would probably like to work on this issue. Can you let me know about the issue properly because I see the images to be proper. 

![image](https://user-images.githubusercontent.com/10096841/30517972-0752ea30-9b3e-11e7-814d-5591d7010fa0.png)

**Comment by isuruAb** [comment]
@Vishesh-Gupta could you please tell me your browser and it's version ? i'm using google chrome

**Comment by sagar-kalra** [comment]
Submitted a PR https://github.com/fossasia/codeheat.org/pull/71
