### ISSUE TITLE
Site in some resolutions on Firefox with large white areas

### ISSUE THREAD

**Issue by hpdang** [fossasia/codeheat.org#78]
![screenshot from 2017-09-21 18-06-47](https://user-images.githubusercontent.com/1658742/30706118-b07dbace-9ef7-11e7-8c22-24d3abf932e0.png)

**Comment by AshishkrGoyal** [comment]
@hpdang same issue is for chrome browser..
markup should be updated for resolving this issue 👍 

![image](https://user-images.githubusercontent.com/25322851/30746143-5fe8fdf6-9fc6-11e7-9d9d-0c605a1a92dc.png)


![image](https://user-images.githubusercontent.com/25322851/30746181-802fb96a-9fc6-11e7-92ce-76dee8abcffb.png)

**Comment by AshishkrGoyal** [comment]
@hpdang can i work on this ?
thanks in advance 👍

**Comment by hpdang** [comment]
@AshishkrGoyal Sure, go ahead.

**Comment by vaibhavsingh97** [comment]
@AshishkrGoyal Are you still working on this?

**Comment by AshishkrGoyal** [comment]
@vaibhavsingh97 
yes i am working on this and send PR as soon as possible 😄

**Comment by sagar-kalra** [comment]
@AshishkrGoyal Still working? Its been a long time.

**Comment by AshishkrGoyal** [comment]
@sagar-kalra if you want to work for it then sure go ahead..
actually i am busy with some other stuff now-a-days 👍 

Thanks 👍
