### ISSUE TITLE
issue in mentor section:unnecessary white space

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/codeheat.org#82]
@mariobehling  Sir.
As per given screenshot for that particular screen size this is a bug:
image size must be equal for resolving this issue 😄 

![image](https://user-images.githubusercontent.com/25322851/30746437-6d3a2966-9fc7-11e7-8d6a-33fd05dfe6b7.png)

Thanks 👍

**Comment by sagar-kalra** [comment]
Created a PR https://github.com/fossasia/codeheat.org/pull/86 .
Please review it.
