### ISSUE TITLE
Minor UI enhancements

### ISSUE THREAD

**Issue by ajayns** [fossasia/codeheat.org#88]
Looking at the site, I noticed a few improvements could be made to the overall look and feel of the design. Attached are screenshots and suggested changes:

![screenshot from 2017-09-26 02-00-22](https://user-images.githubusercontent.com/20743219/30829560-be9e716a-a25e-11e7-90d6-5f280b3c79f6.png)
The padding needs to be fixed for this sign up button as it appears to be broken or not designed well. As an alternative both the buttons here could also be styled to resemble the subscribe input form that appears later.

![screenshot from 2017-09-26 01-59-27](https://user-images.githubusercontent.com/20743219/30829620-f51662c0-a25e-11e7-8731-b26cdb4ca0cc.png)
Here the links such as Website, Chat, Repositories and so on are just plain yellow. I suggest being links, they turn to dark yellow on hover to give the effect that the links are clickable.

![screenshot from 2017-09-26 01-58-20](https://user-images.githubusercontent.com/20743219/30829693-278f476c-a25f-11e7-80fa-864e29a17ed4.png)
The icons seems to be of different sizes and not matching the sizing of each other. Also as an improvement the icons could change color on hover, like facebook turns blue.

I'd like to contribute to this project if you think these are necessary changes.

**Comment by mariobehling** [comment]
Hi, we just made this site quickly using some template components. It is not the goal to make the most stylish site. We just want to have some way to put out information.

Please help with the actual software projects of FOSSASIA. Closing this due to low priority. Thanks.

**Comment by ajayns** [comment]
@mariobehling  Hey! I understand, I assumed it was up for long term dev and improvements. Anyways, I'm a frontend developer primarily working on Angular/Ionic and also CSS and its frameworks. Which projects would you suggest I look into if I'd like to contribute?

**Comment by mariobehling** [comment]
@ajayns Please check out https://github.com/fossasia/susper.com

Please join the chat on for any questions. There are many community members who would be happy to help you onboarding. https://github.com/fossasia/susper.com
