### ISSUE TITLE
find and fix typos on site

### ISSUE THREAD

**Issue by PAPERPANKS** [fossasia/codeheat.org#98]

**Comment by madhurgupta10** [comment]
Working on it!

**Comment by 0x48piraj** [comment]
Still working @madhurgupta10 ?

**Comment by madhurgupta10** [comment]
@0x48piraj Hi, I thought this issue was resolved so I stopped working on it. Are there any typos still pending to be fixed?

**Comment by 0x48piraj** [comment]
So, you should a ask @mariobehling to close this issue :wink: 

> It's our job to clean up the issues so that new-devs don't waste their time :blush:

**Comment by madhurgupta10** [comment]
@0x48piraj luckily found another typo 😉[https://github.com/fossasia/codeheat.org/pull/102](url)

**Comment by abishekvashok** [comment]
I hope this is this fixed @madhurgupta10 genre closing this. We can have new issues if you find more!
